/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const UserType = IDL.Variant({
  'teacher' : IDL.Null,
  'superAdmin' : IDL.Null,
  'schoolAdmin' : IDL.Null,
  'student' : IDL.Null,
});
export const UserProfile = IDL.Record({
  'userType' : UserType,
  'userId' : IDL.Nat,
  'schoolId' : IDL.Opt(IDL.Nat),
});
export const Class = IDL.Record({
  'id' : IDL.Nat,
  'arm' : IDL.Text,
  'schoolId' : IDL.Nat,
  'classLevel' : IDL.Text,
  'className' : IDL.Text,
});
export const School = IDL.Record({
  'id' : IDL.Nat,
  'isApproved' : IDL.Bool,
  'username' : IDL.Text,
  'password' : IDL.Text,
  'name' : IDL.Text,
  'email' : IDL.Text,
  'address' : IDL.Text,
  'phone' : IDL.Text,
});
export const Score = IDL.Record({
  'id' : IDL.Nat,
  'ca1' : IDL.Nat,
  'ca2' : IDL.Nat,
  'total' : IDL.Nat,
  'studentId' : IDL.Nat,
  'exam' : IDL.Nat,
  'grade' : IDL.Text,
  'subjectId' : IDL.Nat,
  'teacherId' : IDL.Nat,
  'sessionId' : IDL.Nat,
  'termId' : IDL.Nat,
});
export const Session = IDL.Record({
  'id' : IDL.Nat,
  'name' : IDL.Text,
  'isActive' : IDL.Bool,
  'schoolId' : IDL.Nat,
});
export const Student = IDL.Record({
  'id' : IDL.Nat,
  'password' : IDL.Text,
  'parentPhone' : IDL.Text,
  'fullName' : IDL.Text,
  'classId' : IDL.Nat,
  'admissionNumber' : IDL.Text,
  'schoolId' : IDL.Nat,
  'gender' : IDL.Text,
  'parentName' : IDL.Text,
});
export const Subject = IDL.Record({
  'id' : IDL.Nat,
  'code' : IDL.Text,
  'name' : IDL.Text,
  'assignedClasses' : IDL.Vec(IDL.Nat),
  'schoolId' : IDL.Nat,
  'teacherId' : IDL.Opt(IDL.Nat),
});
export const Teacher = IDL.Record({
  'id' : IDL.Nat,
  'username' : IDL.Text,
  'password' : IDL.Text,
  'fullName' : IDL.Text,
  'email' : IDL.Text,
  'schoolId' : IDL.Nat,
  'address' : IDL.Text,
  'phone' : IDL.Text,
});
export const Term = IDL.Record({
  'id' : IDL.Nat,
  'name' : IDL.Text,
  'isActive' : IDL.Bool,
  'schoolId' : IDL.Nat,
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'activateSession' : IDL.Func([IDL.Nat], [], []),
  'activateTerm' : IDL.Func([IDL.Nat], [], []),
  'addClass' : IDL.Func([IDL.Nat, IDL.Text, IDL.Text, IDL.Text], [IDL.Nat], []),
  'addSession' : IDL.Func([IDL.Nat, IDL.Text], [IDL.Nat], []),
  'addStudent' : IDL.Func(
      [
        IDL.Nat,
        IDL.Text,
        IDL.Text,
        IDL.Nat,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
      ],
      [IDL.Nat],
      [],
    ),
  'addSubject' : IDL.Func(
      [IDL.Nat, IDL.Text, IDL.Text, IDL.Vec(IDL.Nat), IDL.Opt(IDL.Nat)],
      [IDL.Nat],
      [],
    ),
  'addTeacher' : IDL.Func(
      [IDL.Nat, IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
      [IDL.Nat],
      [],
    ),
  'addTerm' : IDL.Func([IDL.Nat, IDL.Text], [IDL.Nat], []),
  'approveSchool' : IDL.Func([IDL.Nat], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'enterScore' : IDL.Func(
      [IDL.Nat, IDL.Nat, IDL.Nat, IDL.Nat, IDL.Nat, IDL.Nat, IDL.Nat, IDL.Nat],
      [IDL.Nat],
      [],
    ),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getClass' : IDL.Func([IDL.Nat], [IDL.Opt(Class)], ['query']),
  'getSchool' : IDL.Func([IDL.Nat], [IDL.Opt(School)], ['query']),
  'getScore' : IDL.Func([IDL.Nat], [IDL.Opt(Score)], ['query']),
  'getSession' : IDL.Func([IDL.Nat], [IDL.Opt(Session)], ['query']),
  'getStudent' : IDL.Func([IDL.Nat], [IDL.Opt(Student)], ['query']),
  'getStudentScores' : IDL.Func([IDL.Nat], [IDL.Vec(Score)], ['query']),
  'getSubject' : IDL.Func([IDL.Nat], [IDL.Opt(Subject)], ['query']),
  'getTeacher' : IDL.Func([IDL.Nat], [IDL.Opt(Teacher)], ['query']),
  'getTerm' : IDL.Func([IDL.Nat], [IDL.Opt(Term)], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'listAllSchools' : IDL.Func([], [IDL.Vec(School)], ['query']),
  'loginSchoolAdmin' : IDL.Func([IDL.Text, IDL.Text], [IDL.Opt(IDL.Nat)], []),
  'loginStudent' : IDL.Func([IDL.Text, IDL.Text], [IDL.Opt(IDL.Nat)], []),
  'loginSuperAdmin' : IDL.Func([IDL.Text, IDL.Text], [IDL.Bool], []),
  'loginTeacher' : IDL.Func([IDL.Text, IDL.Text], [IDL.Opt(IDL.Nat)], []),
  'registerSchool' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
      [IDL.Nat],
      [],
    ),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'searchClassesByName' : IDL.Func(
      [IDL.Nat, IDL.Text],
      [IDL.Vec(Class)],
      ['query'],
    ),
  'searchStudentsByName' : IDL.Func(
      [IDL.Nat, IDL.Text],
      [IDL.Vec(Student)],
      ['query'],
    ),
  'searchSubjectsByName' : IDL.Func(
      [IDL.Nat, IDL.Text],
      [IDL.Vec(Subject)],
      ['query'],
    ),
  'searchTeachersByName' : IDL.Func(
      [IDL.Nat, IDL.Text],
      [IDL.Vec(Teacher)],
      ['query'],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const UserType = IDL.Variant({
    'teacher' : IDL.Null,
    'superAdmin' : IDL.Null,
    'schoolAdmin' : IDL.Null,
    'student' : IDL.Null,
  });
  const UserProfile = IDL.Record({
    'userType' : UserType,
    'userId' : IDL.Nat,
    'schoolId' : IDL.Opt(IDL.Nat),
  });
  const Class = IDL.Record({
    'id' : IDL.Nat,
    'arm' : IDL.Text,
    'schoolId' : IDL.Nat,
    'classLevel' : IDL.Text,
    'className' : IDL.Text,
  });
  const School = IDL.Record({
    'id' : IDL.Nat,
    'isApproved' : IDL.Bool,
    'username' : IDL.Text,
    'password' : IDL.Text,
    'name' : IDL.Text,
    'email' : IDL.Text,
    'address' : IDL.Text,
    'phone' : IDL.Text,
  });
  const Score = IDL.Record({
    'id' : IDL.Nat,
    'ca1' : IDL.Nat,
    'ca2' : IDL.Nat,
    'total' : IDL.Nat,
    'studentId' : IDL.Nat,
    'exam' : IDL.Nat,
    'grade' : IDL.Text,
    'subjectId' : IDL.Nat,
    'teacherId' : IDL.Nat,
    'sessionId' : IDL.Nat,
    'termId' : IDL.Nat,
  });
  const Session = IDL.Record({
    'id' : IDL.Nat,
    'name' : IDL.Text,
    'isActive' : IDL.Bool,
    'schoolId' : IDL.Nat,
  });
  const Student = IDL.Record({
    'id' : IDL.Nat,
    'password' : IDL.Text,
    'parentPhone' : IDL.Text,
    'fullName' : IDL.Text,
    'classId' : IDL.Nat,
    'admissionNumber' : IDL.Text,
    'schoolId' : IDL.Nat,
    'gender' : IDL.Text,
    'parentName' : IDL.Text,
  });
  const Subject = IDL.Record({
    'id' : IDL.Nat,
    'code' : IDL.Text,
    'name' : IDL.Text,
    'assignedClasses' : IDL.Vec(IDL.Nat),
    'schoolId' : IDL.Nat,
    'teacherId' : IDL.Opt(IDL.Nat),
  });
  const Teacher = IDL.Record({
    'id' : IDL.Nat,
    'username' : IDL.Text,
    'password' : IDL.Text,
    'fullName' : IDL.Text,
    'email' : IDL.Text,
    'schoolId' : IDL.Nat,
    'address' : IDL.Text,
    'phone' : IDL.Text,
  });
  const Term = IDL.Record({
    'id' : IDL.Nat,
    'name' : IDL.Text,
    'isActive' : IDL.Bool,
    'schoolId' : IDL.Nat,
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'activateSession' : IDL.Func([IDL.Nat], [], []),
    'activateTerm' : IDL.Func([IDL.Nat], [], []),
    'addClass' : IDL.Func(
        [IDL.Nat, IDL.Text, IDL.Text, IDL.Text],
        [IDL.Nat],
        [],
      ),
    'addSession' : IDL.Func([IDL.Nat, IDL.Text], [IDL.Nat], []),
    'addStudent' : IDL.Func(
        [
          IDL.Nat,
          IDL.Text,
          IDL.Text,
          IDL.Nat,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
        ],
        [IDL.Nat],
        [],
      ),
    'addSubject' : IDL.Func(
        [IDL.Nat, IDL.Text, IDL.Text, IDL.Vec(IDL.Nat), IDL.Opt(IDL.Nat)],
        [IDL.Nat],
        [],
      ),
    'addTeacher' : IDL.Func(
        [IDL.Nat, IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
        [IDL.Nat],
        [],
      ),
    'addTerm' : IDL.Func([IDL.Nat, IDL.Text], [IDL.Nat], []),
    'approveSchool' : IDL.Func([IDL.Nat], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'enterScore' : IDL.Func(
        [
          IDL.Nat,
          IDL.Nat,
          IDL.Nat,
          IDL.Nat,
          IDL.Nat,
          IDL.Nat,
          IDL.Nat,
          IDL.Nat,
        ],
        [IDL.Nat],
        [],
      ),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getClass' : IDL.Func([IDL.Nat], [IDL.Opt(Class)], ['query']),
    'getSchool' : IDL.Func([IDL.Nat], [IDL.Opt(School)], ['query']),
    'getScore' : IDL.Func([IDL.Nat], [IDL.Opt(Score)], ['query']),
    'getSession' : IDL.Func([IDL.Nat], [IDL.Opt(Session)], ['query']),
    'getStudent' : IDL.Func([IDL.Nat], [IDL.Opt(Student)], ['query']),
    'getStudentScores' : IDL.Func([IDL.Nat], [IDL.Vec(Score)], ['query']),
    'getSubject' : IDL.Func([IDL.Nat], [IDL.Opt(Subject)], ['query']),
    'getTeacher' : IDL.Func([IDL.Nat], [IDL.Opt(Teacher)], ['query']),
    'getTerm' : IDL.Func([IDL.Nat], [IDL.Opt(Term)], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'listAllSchools' : IDL.Func([], [IDL.Vec(School)], ['query']),
    'loginSchoolAdmin' : IDL.Func([IDL.Text, IDL.Text], [IDL.Opt(IDL.Nat)], []),
    'loginStudent' : IDL.Func([IDL.Text, IDL.Text], [IDL.Opt(IDL.Nat)], []),
    'loginSuperAdmin' : IDL.Func([IDL.Text, IDL.Text], [IDL.Bool], []),
    'loginTeacher' : IDL.Func([IDL.Text, IDL.Text], [IDL.Opt(IDL.Nat)], []),
    'registerSchool' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
        [IDL.Nat],
        [],
      ),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'searchClassesByName' : IDL.Func(
        [IDL.Nat, IDL.Text],
        [IDL.Vec(Class)],
        ['query'],
      ),
    'searchStudentsByName' : IDL.Func(
        [IDL.Nat, IDL.Text],
        [IDL.Vec(Student)],
        ['query'],
      ),
    'searchSubjectsByName' : IDL.Func(
        [IDL.Nat, IDL.Text],
        [IDL.Vec(Subject)],
        ['query'],
      ),
    'searchTeachersByName' : IDL.Func(
        [IDL.Nat, IDL.Text],
        [IDL.Vec(Teacher)],
        ['query'],
      ),
  });
};

export const init = ({ IDL }) => { return []; };