/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Class {
  'id' : bigint,
  'arm' : string,
  'schoolId' : bigint,
  'classLevel' : string,
  'className' : string,
}
export interface School {
  'id' : bigint,
  'isApproved' : boolean,
  'username' : string,
  'password' : string,
  'name' : string,
  'email' : string,
  'address' : string,
  'phone' : string,
}
export interface Score {
  'id' : bigint,
  'ca1' : bigint,
  'ca2' : bigint,
  'total' : bigint,
  'studentId' : bigint,
  'exam' : bigint,
  'grade' : string,
  'subjectId' : bigint,
  'teacherId' : bigint,
  'sessionId' : bigint,
  'termId' : bigint,
}
export interface Session {
  'id' : bigint,
  'name' : string,
  'isActive' : boolean,
  'schoolId' : bigint,
}
export interface Student {
  'id' : bigint,
  'password' : string,
  'parentPhone' : string,
  'fullName' : string,
  'classId' : bigint,
  'admissionNumber' : string,
  'schoolId' : bigint,
  'gender' : string,
  'parentName' : string,
}
export interface Subject {
  'id' : bigint,
  'code' : string,
  'name' : string,
  'assignedClasses' : Array<bigint>,
  'schoolId' : bigint,
  'teacherId' : [] | [bigint],
}
export interface Teacher {
  'id' : bigint,
  'username' : string,
  'password' : string,
  'fullName' : string,
  'email' : string,
  'schoolId' : bigint,
  'address' : string,
  'phone' : string,
}
export interface Term {
  'id' : bigint,
  'name' : string,
  'isActive' : boolean,
  'schoolId' : bigint,
}
export interface UserProfile {
  'userType' : UserType,
  'userId' : bigint,
  'schoolId' : [] | [bigint],
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export type UserType = { 'teacher' : null } |
  { 'superAdmin' : null } |
  { 'schoolAdmin' : null } |
  { 'student' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'activateSession' : ActorMethod<[bigint], undefined>,
  'activateTerm' : ActorMethod<[bigint], undefined>,
  'addClass' : ActorMethod<[bigint, string, string, string], bigint>,
  'addSession' : ActorMethod<[bigint, string], bigint>,
  'addStudent' : ActorMethod<
    [bigint, string, string, bigint, string, string, string, string],
    bigint
  >,
  'addSubject' : ActorMethod<
    [bigint, string, string, Array<bigint>, [] | [bigint]],
    bigint
  >,
  'addTeacher' : ActorMethod<
    [bigint, string, string, string, string, string, string],
    bigint
  >,
  'addTerm' : ActorMethod<[bigint, string], bigint>,
  'approveSchool' : ActorMethod<[bigint], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'enterScore' : ActorMethod<
    [bigint, bigint, bigint, bigint, bigint, bigint, bigint, bigint],
    bigint
  >,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getClass' : ActorMethod<[bigint], [] | [Class]>,
  'getSchool' : ActorMethod<[bigint], [] | [School]>,
  'getScore' : ActorMethod<[bigint], [] | [Score]>,
  'getSession' : ActorMethod<[bigint], [] | [Session]>,
  'getStudent' : ActorMethod<[bigint], [] | [Student]>,
  'getStudentScores' : ActorMethod<[bigint], Array<Score>>,
  'getSubject' : ActorMethod<[bigint], [] | [Subject]>,
  'getTeacher' : ActorMethod<[bigint], [] | [Teacher]>,
  'getTerm' : ActorMethod<[bigint], [] | [Term]>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'listAllSchools' : ActorMethod<[], Array<School>>,
  'loginSchoolAdmin' : ActorMethod<[string, string], [] | [bigint]>,
  'loginStudent' : ActorMethod<[string, string], [] | [bigint]>,
  'loginSuperAdmin' : ActorMethod<[string, string], boolean>,
  'loginTeacher' : ActorMethod<[string, string], [] | [bigint]>,
  'registerSchool' : ActorMethod<
    [string, string, string, string, string, string],
    bigint
  >,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'searchClassesByName' : ActorMethod<[bigint, string], Array<Class>>,
  'searchStudentsByName' : ActorMethod<[bigint, string], Array<Student>>,
  'searchSubjectsByName' : ActorMethod<[bigint, string], Array<Subject>>,
  'searchTeachersByName' : ActorMethod<[bigint, string], Array<Teacher>>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];