/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface Class {
    id: bigint;
    arm: string;
    schoolId: bigint;
    classLevel: string;
    className: string;
}
export interface Session {
    id: bigint;
    name: string;
    isActive: boolean;
    schoolId: bigint;
}
export interface Term {
    id: bigint;
    name: string;
    isActive: boolean;
    schoolId: bigint;
}
export interface Score {
    id: bigint;
    ca1: bigint;
    ca2: bigint;
    total: bigint;
    studentId: bigint;
    exam: bigint;
    grade: string;
    subjectId: bigint;
    teacherId: bigint;
    sessionId: bigint;
    termId: bigint;
}
export interface School {
    id: bigint;
    isApproved: boolean;
    username: string;
    password: string;
    name: string;
    email: string;
    address: string;
    phone: string;
}
export interface SchoolBranding {
    schoolId: bigint;
    motto: string;
    websiteUrl: string;
    logoBase64: string;
    stampBase64: string;
    signatureBase64: string;
}
export interface Teacher {
    id: bigint;
    username: string;
    password: string;
    fullName: string;
    email: string;
    schoolId: bigint;
    address: string;
    phone: string;
}
export interface Subject {
    id: bigint;
    code: string;
    name: string;
    assignedClasses: Array<bigint>;
    schoolId: bigint;
    teacherId?: bigint;
}
export interface UserProfile {
    userType: UserType;
    userId: bigint;
    schoolId?: bigint;
}
export interface Student {
    id: bigint;
    password: string;
    parentPhone: string;
    fullName: string;
    classId: bigint;
    admissionNumber: string;
    schoolId: bigint;
    gender: string;
    parentName: string;
}
export enum UserRole {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export enum UserType {
    teacher = "teacher",
    superAdmin = "superAdmin",
    schoolAdmin = "schoolAdmin",
    student = "student"
}
export interface backendInterface {
    _initializeAccessControlWithSecret(userSecret: string): Promise<void>;
    activateSession(sessionId: bigint): Promise<void>;
    activateTerm(termId: bigint): Promise<void>;
    addClass(schoolId: bigint, classLevel: string, className: string, arm: string): Promise<bigint>;
    addSession(schoolId: bigint, name: string): Promise<bigint>;
    addStudent(schoolId: bigint, fullName: string, gender: string, classId: bigint, admissionNumber: string, parentName: string, parentPhone: string, password: string): Promise<bigint>;
    addSubject(schoolId: bigint, name: string, code: string, assignedClasses: Array<bigint>, teacherId: bigint | null): Promise<bigint>;
    addTeacher(schoolId: bigint, fullName: string, username: string, phone: string, email: string, address: string, password: string): Promise<bigint>;
    addTerm(schoolId: bigint, name: string): Promise<bigint>;
    approveSchool(schoolId: bigint): Promise<void>;
    assignCallerUserRole(user: Principal, role: UserRole): Promise<void>;
    enterScore(studentId: bigint, subjectId: bigint, teacherId: bigint, sessionId: bigint, termId: bigint, ca1: bigint, ca2: bigint, exam: bigint): Promise<bigint>;
    getCallerUserProfile(): Promise<UserProfile | null>;
    getCallerUserRole(): Promise<UserRole>;
    getClass(id: bigint): Promise<Class | null>;
    getSchool(id: bigint): Promise<School | null>;
    getScore(id: bigint): Promise<Score | null>;
    getSession(id: bigint): Promise<Session | null>;
    getStudent(id: bigint): Promise<Student | null>;
    getStudentScores(studentId: bigint): Promise<Array<Score>>;
    getSubject(id: bigint): Promise<Subject | null>;
    getTeacher(id: bigint): Promise<Teacher | null>;
    getTerm(id: bigint): Promise<Term | null>;
    getUserProfile(user: Principal): Promise<UserProfile | null>;
    isCallerAdmin(): Promise<boolean>;
    listAllSchools(): Promise<Array<School>>;
    listClasses(schoolId: bigint): Promise<Array<Class>>;
    listSessions(schoolId: bigint): Promise<Array<Session>>;
    listStudents(schoolId: bigint): Promise<Array<Student>>;
    listSubjects(schoolId: bigint): Promise<Array<Subject>>;
    listTeachers(schoolId: bigint): Promise<Array<Teacher>>;
    listTerms(schoolId: bigint): Promise<Array<Term>>;
    loginSchoolAdmin(username: string, password: string): Promise<bigint | null>;
    loginStudent(admissionNumber: string, password: string): Promise<bigint | null>;
    loginSuperAdmin(email: string, password: string): Promise<boolean>;
    loginTeacher(username: string, password: string): Promise<bigint | null>;
    registerSchool(name: string, email: string, phone: string, address: string, username: string, password: string): Promise<bigint>;
    saveCallerUserProfile(profile: UserProfile): Promise<void>;
    searchClassesByName(schoolId: bigint, name: string): Promise<Array<Class>>;
    searchStudentsByName(schoolId: bigint, name: string): Promise<Array<Student>>;
    searchSubjectsByName(schoolId: bigint, name: string): Promise<Array<Subject>>;
    searchTeachersByName(schoolId: bigint, name: string): Promise<Array<Teacher>>;
    deleteClass(classId: bigint): Promise<void>;
    deleteStudent(studentId: bigint): Promise<void>;
    deleteSubject(subjectId: bigint): Promise<void>;
    deleteTeacher(teacherId: bigint): Promise<void>;
    getStudentSelf(): Promise<Student | null>;
    getTeacherSelf(): Promise<Teacher | null>;
    getSchoolSelf(): Promise<School | null>;
    updateClass(classId: bigint, classLevel: string, className: string, arm: string): Promise<void>;
    updateStudent(studentId: bigint, fullName: string, gender: string, classId: bigint, admissionNumber: string, parentName: string, parentPhone: string): Promise<void>;
    updateSubject(subjectId: bigint, name: string, code: string, assignedClasses: Array<bigint>, teacherId: bigint | null): Promise<void>;
    updateTeacher(teacherId: bigint, fullName: string, username: string, phone: string, email: string, address: string): Promise<void>;
    getSchoolBranding(schoolId: bigint): Promise<SchoolBranding | null>;
    updateSchoolBranding(schoolId: bigint, motto: string, websiteUrl: string, logoBase64: string, stampBase64: string, signatureBase64: string): Promise<void>;
}
import type { Class as _Class, School as _School, Score as _Score, Session as _Session, Student as _Student, Subject as _Subject, Teacher as _Teacher, Term as _Term, UserProfile as _UserProfile, UserRole as _UserRole, UserType as _UserType } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _initializeAccessControlWithSecret(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._initializeAccessControlWithSecret(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._initializeAccessControlWithSecret(arg0);
            return result;
        }
    }
    async activateSession(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.activateSession(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.activateSession(arg0);
            return result;
        }
    }
    async activateTerm(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.activateTerm(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.activateTerm(arg0);
            return result;
        }
    }
    async addClass(arg0: bigint, arg1: string, arg2: string, arg3: string): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.addClass(arg0, arg1, arg2, arg3);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addClass(arg0, arg1, arg2, arg3);
            return result;
        }
    }
    async addSession(arg0: bigint, arg1: string): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.addSession(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addSession(arg0, arg1);
            return result;
        }
    }
    async addStudent(arg0: bigint, arg1: string, arg2: string, arg3: bigint, arg4: string, arg5: string, arg6: string, arg7: string): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.addStudent(arg0, arg1, arg2, arg3, arg4, arg5, arg6, arg7);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addStudent(arg0, arg1, arg2, arg3, arg4, arg5, arg6, arg7);
            return result;
        }
    }
    async addSubject(arg0: bigint, arg1: string, arg2: string, arg3: Array<bigint>, arg4: bigint | null): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.addSubject(arg0, arg1, arg2, arg3, to_candid_opt_n1(this._uploadFile, this._downloadFile, arg4));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addSubject(arg0, arg1, arg2, arg3, to_candid_opt_n1(this._uploadFile, this._downloadFile, arg4));
            return result;
        }
    }
    async addTeacher(arg0: bigint, arg1: string, arg2: string, arg3: string, arg4: string, arg5: string, arg6: string): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.addTeacher(arg0, arg1, arg2, arg3, arg4, arg5, arg6);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addTeacher(arg0, arg1, arg2, arg3, arg4, arg5, arg6);
            return result;
        }
    }
    async addTerm(arg0: bigint, arg1: string): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.addTerm(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addTerm(arg0, arg1);
            return result;
        }
    }
    async approveSchool(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.approveSchool(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.approveSchool(arg0);
            return result;
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n2(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n2(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async enterScore(arg0: bigint, arg1: bigint, arg2: bigint, arg3: bigint, arg4: bigint, arg5: bigint, arg6: bigint, arg7: bigint): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.enterScore(arg0, arg1, arg2, arg3, arg4, arg5, arg6, arg7);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.enterScore(arg0, arg1, arg2, arg3, arg4, arg5, arg6, arg7);
            return result;
        }
    }
    async getCallerUserProfile(): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserProfile();
                return from_candid_opt_n4(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserProfile();
            return from_candid_opt_n4(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserRole(): Promise<UserRole> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole_n10(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole_n10(this._uploadFile, this._downloadFile, result);
        }
    }
    async getClass(arg0: bigint): Promise<Class | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getClass(arg0);
                return from_candid_opt_n12(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getClass(arg0);
            return from_candid_opt_n12(this._uploadFile, this._downloadFile, result);
        }
    }
    async getSchool(arg0: bigint): Promise<School | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getSchool(arg0);
                return from_candid_opt_n13(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getSchool(arg0);
            return from_candid_opt_n13(this._uploadFile, this._downloadFile, result);
        }
    }
    async getScore(arg0: bigint): Promise<Score | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getScore(arg0);
                return from_candid_opt_n14(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getScore(arg0);
            return from_candid_opt_n14(this._uploadFile, this._downloadFile, result);
        }
    }
    async getSession(arg0: bigint): Promise<Session | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getSession(arg0);
                return from_candid_opt_n15(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getSession(arg0);
            return from_candid_opt_n15(this._uploadFile, this._downloadFile, result);
        }
    }
    async getStudent(arg0: bigint): Promise<Student | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getStudent(arg0);
                return from_candid_opt_n16(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getStudent(arg0);
            return from_candid_opt_n16(this._uploadFile, this._downloadFile, result);
        }
    }
    async getStudentScores(arg0: bigint): Promise<Array<Score>> {
        if (this.processError) {
            try {
                const result = await this.actor.getStudentScores(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getStudentScores(arg0);
            return result;
        }
    }
    async getSubject(arg0: bigint): Promise<Subject | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getSubject(arg0);
                return from_candid_opt_n17(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getSubject(arg0);
            return from_candid_opt_n17(this._uploadFile, this._downloadFile, result);
        }
    }
    async getTeacher(arg0: bigint): Promise<Teacher | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getTeacher(arg0);
                return from_candid_opt_n20(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getTeacher(arg0);
            return from_candid_opt_n20(this._uploadFile, this._downloadFile, result);
        }
    }
    async deleteClass(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteClass(arg0);
                return result;
            } catch (e) { this.processError(e); throw new Error("unreachable"); }
        } else { return await this.actor.deleteClass(arg0); }
    }
    async deleteStudent(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteStudent(arg0);
                return result;
            } catch (e) { this.processError(e); throw new Error("unreachable"); }
        } else { return await this.actor.deleteStudent(arg0); }
    }
    async deleteSubject(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteSubject(arg0);
                return result;
            } catch (e) { this.processError(e); throw new Error("unreachable"); }
        } else { return await this.actor.deleteSubject(arg0); }
    }
    async deleteTeacher(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteTeacher(arg0);
                return result;
            } catch (e) { this.processError(e); throw new Error("unreachable"); }
        } else { return await this.actor.deleteTeacher(arg0); }
    }
    async getStudentSelf(): Promise<Student | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getStudentSelf();
                return from_candid_opt_n16(this._uploadFile, this._downloadFile, result);
            } catch (e) { this.processError(e); throw new Error("unreachable"); }
        } else {
            const result = await this.actor.getStudentSelf();
            return from_candid_opt_n16(this._uploadFile, this._downloadFile, result);
        }
    }
    async getTeacherSelf(): Promise<Teacher | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getTeacherSelf();
                return from_candid_opt_n20(this._uploadFile, this._downloadFile, result);
            } catch (e) { this.processError(e); throw new Error("unreachable"); }
        } else {
            const result = await this.actor.getTeacherSelf();
            return from_candid_opt_n20(this._uploadFile, this._downloadFile, result);
        }
    }
    async getSchoolSelf(): Promise<School | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getSchoolSelf();
                return from_candid_opt_n13(this._uploadFile, this._downloadFile, result);
            } catch (e) { this.processError(e); throw new Error("unreachable"); }
        } else {
            const result = await this.actor.getSchoolSelf();
            return from_candid_opt_n13(this._uploadFile, this._downloadFile, result);
        }
    }
    async updateClass(arg0: bigint, arg1: string, arg2: string, arg3: string): Promise<void> {
        if (this.processError) {
            try { return await this.actor.updateClass(arg0, arg1, arg2, arg3); }
            catch (e) { this.processError(e); throw new Error("unreachable"); }
        } else { return await this.actor.updateClass(arg0, arg1, arg2, arg3); }
    }
    async updateStudent(arg0: bigint, arg1: string, arg2: string, arg3: bigint, arg4: string, arg5: string, arg6: string): Promise<void> {
        if (this.processError) {
            try { return await this.actor.updateStudent(arg0, arg1, arg2, arg3, arg4, arg5, arg6); }
            catch (e) { this.processError(e); throw new Error("unreachable"); }
        } else { return await this.actor.updateStudent(arg0, arg1, arg2, arg3, arg4, arg5, arg6); }
    }
    async updateSubject(arg0: bigint, arg1: string, arg2: string, arg3: Array<bigint>, arg4: bigint | null): Promise<void> {
        if (this.processError) {
            try { return await this.actor.updateSubject(arg0, arg1, arg2, arg3, arg4 === null ? [] : [arg4]); }
            catch (e) { this.processError(e); throw new Error("unreachable"); }
        } else { return await this.actor.updateSubject(arg0, arg1, arg2, arg3, arg4 === null ? [] : [arg4]); }
    }
    async updateTeacher(arg0: bigint, arg1: string, arg2: string, arg3: string, arg4: string, arg5: string): Promise<void> {
        if (this.processError) {
            try { return await this.actor.updateTeacher(arg0, arg1, arg2, arg3, arg4, arg5); }
            catch (e) { this.processError(e); throw new Error("unreachable"); }
        } else { return await this.actor.updateTeacher(arg0, arg1, arg2, arg3, arg4, arg5); }
    }
    async getSchoolBranding(arg0: bigint): Promise<SchoolBranding | null> {
        if (this.processError) {
            try { const r = await this.actor.getSchoolBranding(arg0); return r.length === 0 ? null : r[0]; }
            catch (e) { this.processError(e); throw new Error("unreachable"); }
        } else { const r = await this.actor.getSchoolBranding(arg0); return r.length === 0 ? null : r[0]; }
    }
    async updateSchoolBranding(arg0: bigint, arg1: string, arg2: string, arg3: string, arg4: string, arg5: string): Promise<void> {
        if (this.processError) {
            try { return await this.actor.updateSchoolBranding(arg0, arg1, arg2, arg3, arg4, arg5); }
            catch (e) { this.processError(e); throw new Error("unreachable"); }
        } else { return await this.actor.updateSchoolBranding(arg0, arg1, arg2, arg3, arg4, arg5); }
    }
    async getTerm(arg0: bigint): Promise<Term | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getTerm(arg0);
                return from_candid_opt_n21(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getTerm(arg0);
            return from_candid_opt_n21(this._uploadFile, this._downloadFile, result);
        }
    }
    async getUserProfile(arg0: Principal): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserProfile(arg0);
                return from_candid_opt_n4(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserProfile(arg0);
            return from_candid_opt_n4(this._uploadFile, this._downloadFile, result);
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async listAllSchools(): Promise<Array<School>> {
        if (this.processError) {
            try {
                const result = await this.actor.listAllSchools();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listAllSchools();
            return result;
        }
    }
    async loginSchoolAdmin(arg0: string, arg1: string): Promise<bigint | null> {
        if (this.processError) {
            try {
                const result = await this.actor.loginSchoolAdmin(arg0, arg1);
                return from_candid_opt_n9(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.loginSchoolAdmin(arg0, arg1);
            return from_candid_opt_n9(this._uploadFile, this._downloadFile, result);
        }
    }
    async loginStudent(arg0: string, arg1: string): Promise<bigint | null> {
        if (this.processError) {
            try {
                const result = await this.actor.loginStudent(arg0, arg1);
                return from_candid_opt_n9(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.loginStudent(arg0, arg1);
            return from_candid_opt_n9(this._uploadFile, this._downloadFile, result);
        }
    }
    async loginSuperAdmin(arg0: string, arg1: string): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.loginSuperAdmin(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.loginSuperAdmin(arg0, arg1);
            return result;
        }
    }
    async loginTeacher(arg0: string, arg1: string): Promise<bigint | null> {
        if (this.processError) {
            try {
                const result = await this.actor.loginTeacher(arg0, arg1);
                return from_candid_opt_n9(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.loginTeacher(arg0, arg1);
            return from_candid_opt_n9(this._uploadFile, this._downloadFile, result);
        }
    }
    async registerSchool(arg0: string, arg1: string, arg2: string, arg3: string, arg4: string, arg5: string): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.registerSchool(arg0, arg1, arg2, arg3, arg4, arg5);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.registerSchool(arg0, arg1, arg2, arg3, arg4, arg5);
            return result;
        }
    }
    async saveCallerUserProfile(arg0: UserProfile): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveCallerUserProfile(to_candid_UserProfile_n22(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveCallerUserProfile(to_candid_UserProfile_n22(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async searchClassesByName(arg0: bigint, arg1: string): Promise<Array<Class>> {
        if (this.processError) {
            try {
                const result = await this.actor.searchClassesByName(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.searchClassesByName(arg0, arg1);
            return result;
        }
    }
    async searchStudentsByName(arg0: bigint, arg1: string): Promise<Array<Student>> {
        if (this.processError) {
            try {
                const result = await this.actor.searchStudentsByName(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.searchStudentsByName(arg0, arg1);
            return result;
        }
    }
    async searchSubjectsByName(arg0: bigint, arg1: string): Promise<Array<Subject>> {
        if (this.processError) {
            try {
                const result = await this.actor.searchSubjectsByName(arg0, arg1);
                return from_candid_vec_n26(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.searchSubjectsByName(arg0, arg1);
            return from_candid_vec_n26(this._uploadFile, this._downloadFile, result);
        }
    }
    async searchTeachersByName(arg0: bigint, arg1: string): Promise<Array<Teacher>> {
        if (this.processError) {
            try {
                const result = await this.actor.searchTeachersByName(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.searchTeachersByName(arg0, arg1);
            return result;
        }
    }
    async listClasses(arg0: bigint): Promise<Array<Class>> {
        if (this.processError) {
            try {
                const result = await this.actor.listClasses(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listClasses(arg0);
            return result;
        }
    }
    async listSessions(arg0: bigint): Promise<Array<Session>> {
        if (this.processError) {
            try {
                const result = await this.actor.listSessions(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listSessions(arg0);
            return result;
        }
    }
    async listStudents(arg0: bigint): Promise<Array<Student>> {
        if (this.processError) {
            try {
                const result = await this.actor.listStudents(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listStudents(arg0);
            return result;
        }
    }
    async listSubjects(arg0: bigint): Promise<Array<Subject>> {
        if (this.processError) {
            try {
                const result = await this.actor.listSubjects(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listSubjects(arg0);
            return result;
        }
    }
    async listTeachers(arg0: bigint): Promise<Array<Teacher>> {
        if (this.processError) {
            try {
                const result = await this.actor.listTeachers(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listTeachers(arg0);
            return result;
        }
    }
    async listTerms(arg0: bigint): Promise<Array<Term>> {
        if (this.processError) {
            try {
                const result = await this.actor.listTerms(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listTerms(arg0);
            return result;
        }
    }
}
function from_candid_Subject_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Subject): Subject {
    return from_candid_record_n19(_uploadFile, _downloadFile, value);
}
function from_candid_UserProfile_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserProfile): UserProfile {
    return from_candid_record_n6(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n11(_uploadFile, _downloadFile, value);
}
function from_candid_UserType_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserType): UserType {
    return from_candid_variant_n8(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Class]): Class | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_School]): School | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Score]): Score | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Session]): Session | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Student]): Student | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Subject]): Subject | null {
    return value.length === 0 ? null : from_candid_Subject_n18(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Teacher]): Teacher | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Term]): Term | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UserProfile]): UserProfile | null {
    return value.length === 0 ? null : from_candid_UserProfile_n5(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [bigint]): bigint | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_record_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    code: string;
    name: string;
    assignedClasses: Array<bigint>;
    schoolId: bigint;
    teacherId: [] | [bigint];
}): {
    id: bigint;
    code: string;
    name: string;
    assignedClasses: Array<bigint>;
    schoolId: bigint;
    teacherId?: bigint;
} {
    return {
        id: value.id,
        code: value.code,
        name: value.name,
        assignedClasses: value.assignedClasses,
        schoolId: value.schoolId,
        teacherId: record_opt_to_undefined(from_candid_opt_n9(_uploadFile, _downloadFile, value.teacherId))
    };
}
function from_candid_record_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    userType: _UserType;
    userId: bigint;
    schoolId: [] | [bigint];
}): {
    userType: UserType;
    userId: bigint;
    schoolId?: bigint;
} {
    return {
        userType: from_candid_UserType_n7(_uploadFile, _downloadFile, value.userType),
        userId: value.userId,
        schoolId: record_opt_to_undefined(from_candid_opt_n9(_uploadFile, _downloadFile, value.schoolId))
    };
}
function from_candid_variant_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
}): UserRole {
    return "admin" in value ? UserRole.admin : "user" in value ? UserRole.user : "guest" in value ? UserRole.guest : value;
}
function from_candid_variant_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    teacher: null;
} | {
    superAdmin: null;
} | {
    schoolAdmin: null;
} | {
    student: null;
}): UserType {
    return "teacher" in value ? UserType.teacher : "superAdmin" in value ? UserType.superAdmin : "schoolAdmin" in value ? UserType.schoolAdmin : "student" in value ? UserType.student : value;
}
function from_candid_vec_n26(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Subject>): Array<Subject> {
    return value.map((x)=>from_candid_Subject_n18(_uploadFile, _downloadFile, x));
}
function to_candid_UserProfile_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserProfile): _UserProfile {
    return to_candid_record_n23(_uploadFile, _downloadFile, value);
}
function to_candid_UserRole_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n3(_uploadFile, _downloadFile, value);
}
function to_candid_UserType_n24(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserType): _UserType {
    return to_candid_variant_n25(_uploadFile, _downloadFile, value);
}
function to_candid_opt_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: bigint | null): [] | [bigint] {
    return value === null ? candid_none() : candid_some(value);
}
function to_candid_record_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    userType: UserType;
    userId: bigint;
    schoolId?: bigint;
}): {
    userType: _UserType;
    userId: bigint;
    schoolId: [] | [bigint];
} {
    return {
        userType: to_candid_UserType_n24(_uploadFile, _downloadFile, value.userType),
        userId: value.userId,
        schoolId: value.schoolId ? candid_some(value.schoolId) : candid_none()
    };
}
function to_candid_variant_n25(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserType): {
    teacher: null;
} | {
    superAdmin: null;
} | {
    schoolAdmin: null;
} | {
    student: null;
} {
    return value == UserType.teacher ? {
        teacher: null
    } : value == UserType.superAdmin ? {
        superAdmin: null
    } : value == UserType.schoolAdmin ? {
        schoolAdmin: null
    } : value == UserType.student ? {
        student: null
    } : value;
}
function to_candid_variant_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
} {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.user ? {
        user: null
    } : value == UserRole.guest ? {
        guest: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
